# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used.


PyTorch a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a $5\times 3$ matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0121, 0.1953, 0.7147],
        [0.4146, 0.7002, 0.7947],
        [0.2790, 0.7877, 0.3338],
        [0.5626, 0.4929, 0.6191],
        [0.3443, 0.6044, 0.2716]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [5]:
x[1:3] = 2
print(x)

tensor([[0.0121, 0.1953, 0.7147],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.5626, 0.4929, 0.6191],
        [0.3443, 0.6044, 0.2716]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [15]:
a = torch.Tensor(2,17)

b = torch.FloatTensor(3,1)

c = torch.LongTensor(5,2,1)

a.fill_(7)

# 4) ByteTensor of size (5,), with middle 3 indices = 1  -> [0, 1, 1, 1, 0]
d = torch.zeros(5, dtype=torch.uint8)  # alias of ByteTensor
d[1:4] = 1
# (alternative using index_fill_)
# idx = torch.tensor([1, 2, 3], dtype=torch.long)
# d.index_fill_(0, idx, 1)

print(a.shape)  # torch.Size([2, 17])
print(b.dtype)  # torch.float32
print(c)        # all 7s, dtype long
print(d)        # tensor([0, 1, 1, 1, 0], dtype=torch.uint8)

torch.Size([2, 17])
torch.float32
tensor([[[0],
         [0]],

        [[0],
         [0]],

        [[0],
         [0]],

        [[0],
         [0]],

        [[0],
         [0]]])
tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [16]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.6520, 0.7936, 1.2874],
        [2.7368, 2.8828, 2.1423],
        [2.9186, 2.0462, 2.5865],
        [0.8403, 1.0185, 0.8632],
        [1.0481, 1.3926, 0.2848]])


### 2.2 Addition: syntax 2

In [17]:
print(torch.add(x, y))

tensor([[0.6520, 0.7936, 1.2874],
        [2.7368, 2.8828, 2.1423],
        [2.9186, 2.0462, 2.5865],
        [0.8403, 1.0185, 0.8632],
        [1.0481, 1.3926, 0.2848]])


### 2.3 Addition: giving an output tensor

In [18]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.6520, 0.7936, 1.2874],
        [2.7368, 2.8828, 2.1423],
        [2.9186, 2.0462, 2.5865],
        [0.8403, 1.0185, 0.8632],
        [1.0481, 1.3926, 0.2848]])


### 2.4 Addition: in-place

adds `x` to `y`

In [19]:
y.add_(x)
print(y)

tensor([[0.6520, 0.7936, 1.2874],
        [2.7368, 2.8828, 2.1423],
        [2.9186, 2.0462, 2.5865],
        [0.8403, 1.0185, 0.8632],
        [1.0481, 1.3926, 0.2848]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [20]:
print(x[:, 1])

tensor([0.1953, 2.0000, 2.0000, 0.4929, 0.6044])


**Read later**: 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [23]:
a = torch.randn(3)

torch.mul(a, 100)


tensor([ -6.9741, -83.4611,  22.0156])

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [24]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [25]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [26]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [27]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a NumPy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [29]:
# 1) Tensor of size (5, 2) containing ones (on CPU by default)
t = torch.ones((5, 2))
print(t.shape, t.dtype, t.device)   # torch.Size([5, 2]) torch.float32 cpu

# 2) Convert to a NumPy array (shares memory with the tensor)
a = t.numpy()
print(type(a), a.shape, a.dtype)    # <class 'numpy.ndarray'> (5, 2) float32

# 3) Convert back to a torch tensor (shares memory if from numpy, stays on CPU)
t2 = torch.from_numpy(a)
print(t2.shape, t2.dtype, t2.device)

# (Optional) Demonstrate shared memory:
a[0, 0] = 7
print(t[0, 0], t2[0, 0])  # both will reflect the change (tensor -> numpy -> tensor)

torch.Size([5, 2]) torch.float32 cpu
<class 'numpy.ndarray'> (5, 2) float32
torch.Size([5, 2]) torch.float32 cpu
tensor(7.) tensor(7.)


## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [28]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
